#!/bin/bash
if (( ${#} == 0 )); then
	while read -sp "Enter plaintext: " i; do
		echo; echo "$i" | xxd | cut -d " " -f 2- | rev | cut -d " " -f 2- | rev | head -1 | sed 's/ //g' | xclip -r -selection clipboard; echo; echo "hex value copied to clipboard"
	for i in {4..1}; do
		echo -n "$i..."
		sleep 1
	done
	echo
	echo "CLASSIFIED" | xclip -r -selection clipboard
	exit
	done
else
	for x in "$@"; do
		echo "$x" | xxd | cut -d " " -f 2- | rev | cut -d " " -f 2- | rev | head -1 | sed 's/ //g'
 	done
fi

